### ISSUE TITLE
環境構築: kubectlが動くようにする

### ISSUE THREAD

**Issue by sarrrrry** [sarrrrry/study_k8s#1]
Goal
- HelloWorldのドキュメント中の kubectl らへんが動けばいい!

**Comment by mohira** [comment]
チュートリアルはこれ。

[Hello Minikube - Kubernetes](https://kubernetes.io/ja/docs/tutorials/hello-minikube/)

**Comment by mohira** [comment]
- `kubectl get events` でログっぽいものがみれる
- `kubectl logs` というようなコマンドはなかった

**Comment by sarrrrry** [comment]
### 実施事項
- ローカルのDocker ImageからのPodの作成に失敗した!
    - 色々やってみたけど、結果上手く行かず。
        - ImagePullPolicyの設定
        - Imageのpull対象をDockerHubからローカルにむけた
- チュートリアルを進めた!
- チュートリアルをマニフェストで実行した!

### 学び
登場人物の理解が深まった。
- Deployment 
    - Podを作成したり、監視したい
- Service 
    - serviceを経由しないと、clusterの中にアクセス出来ない
- Pod

### 今後やりたいこと
- Deploymentのself healingの件 >>> #3
    - Podを落としたら本当に起動するのか検証したい
